### ISSUE TITLE
[QUESTION] Stheno or AbstractGPs.jl?

### ISSUE THREAD

**Issue by vikram-s-narayan** [JuliaGaussianProcesses/Stheno.jl#231]
Could you please elaborate on how to choose between Stheno and AbstractGPs.jl. For what use cases would a developer choose one over the other.

Specifically, I'm trying to update [SthenoKriging.jl](https://github.com/SciML/Surrogates.jl/blob/master/src/SthenoKriging.jl) (which used Stheno 0.6) and am wondering how to proceed. 

Thanks!

**Comment by willtebbutt** [comment]
Good question!

You should just use the `GP` object in AbstractGPs if you just need a GP that's most easily written using a mean function and a kernel. You should consider using Stheno if you need to combine individual GPs in interesting ways.

Could you perhaps elaborate on the model used in SthenoKriging.jl?

**Comment by vikram-s-narayan** [comment]
Thank you for the quick and clear response. 

Based on my review of the source code, the test cases and the [documentation](https://surrogates.sciml.ai/v1.0/stheno/), it is my understanding that SthenoKriging.jl is designed to:

1. Fit a model based on a set of input points and corresponding values 
2. Provide a prediction and standard error for any new interpolated point

The model does not combine individual GPs.

**Comment by willtebbutt** [comment]
Ah I see.

My impression from what I can see in the docs is that you'll probably be fine just using an `AbstractGPs.GP` for all of the single-output stuff. If you've got multiple outputs, you can either use Stheno, or one of the multi-output kernels found [here](https://juliagaussianprocesses.github.io/KernelFunctions.jl/dev/kernels/#Multi-output-Kernels) + an `AbstractGPs.GP`.

One thing to be aware of is that literally everything in the `AbstractGPs` ecosystem reduces to a single-output GP, so if you just assume that the user provides an `AbstractGP`, you shouldn't stop users from using any of the above options.

**Comment by vikram-s-narayan** [comment]
Thank you again. I'm closing this issue as the question has been answered :)

**Comment by st--** [comment]
@vikram-s-narayan - I recently came across Surrogates.jl and was looking at the Kriging.jl and SthenoKriging.jl and was thinking they do need a bunch of clean-up & TLC. We'd be happy to help you get it working with the up-to-date AbstractGPs package - if you like, please join us on the Turing slack via this invite link: https://join.slack.com/t/turingjl/shared_invite/zt-ubbtg7r8-xtg4WjXEQTG_jvE~estuKw - and join the discussion in #gp-julia channel :)

**Comment by vikram-s-narayan** [comment]
> @vikram-s-narayan - I recently came across Surrogates.jl and was looking at the Kriging.jl and SthenoKriging.jl and was thinking they do need a bunch of clean-up & TLC. We'd be happy to help you get it working with the up-to-date AbstractGPs package - if you like, please join us on the Turing slack via this invite link: https://join.slack.com/t/turingjl/shared_invite/zt-ubbtg7r8-xtg4WjXEQTG_jvE~estuKw - and join the discussion in #gp-julia channel :)

Thanks!
