### ISSUE TITLE
Sparse Approximations and Non-Gaussian Likelihoods

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/Stheno.jl#36]
As a baseline, Stheno really needs to have [1] implemented. This will be _very_ simple to achieve, and will likely only be a slight extension of the implementation of [2], the elbo for which can be found [here](https://github.com/willtebbutt/Stheno.jl/blob/f09fe29ed01f44e5f44c10029e436c858254d360/src/abstract_gp.jl#L94).

It also seems sensible for Stheno to have at least a _baseline_ implementation that can handle non-Gaussian likelihoods, even if it's not the fanciest most hot-off-the-press thing going. For example, [3] implemented with Monte Carlo sampling to estimate the intractable likelihood expectations would be a good place to start, or perhaps an implementation of [4], which also shouldn't be too hard.

The most important component of each of these is an `elbo` function. For models with Gaussian likelihoods, it's probably sufficient with a similar interface to the current interface:
```julia
elbo(f::FiniteGP, y::AV{<:Real}, u::FiniteGP)
```
but perhaps with some extra arguments for declare the size of the mini-batch and the number of Monte Carlo samples to use. A simple extension of the `FiniteGP` type would probably be the best bet for non-conjugate likelihoods - you would just need a collection of types that would specify what the likelihood you want to use is, and how it's parametrised in terms of the GP in question. Something quite and dirty here would be the best bet - it would be just be helpful to have the functionality, even if the interface isn't ideal.

For those methods that demand natural gradients, I imagine the interface will follow naturally once the `elbo` interface has been determined.

This issue shouldn't be a lot of work for someone who knows the literature below reasonably well.

[1] - Hensman, James, Nicolo Fusi, and Neil D. Lawrence. "Gaussian processes for big data." arXiv preprint arXiv:1309.6835 (2013).
[2] - Titsias, Michalis. "Variational learning of inducing variables in sparse Gaussian processes." Artificial Intelligence and Statistics. 2009.
[3] - Hensman, James, Alexander Matthews, and Zoubin Ghahramani. "Scalable variational Gaussian process classification." (2015).
[4] - Salimbeni, Hugh, Stefanos Eleftheriadis, and James Hensman. "Natural gradients in practice: Non-conjugate variational inference in Gaussian process models." arXiv preprint arXiv:1803.09151 (2018).

**Comment by SaremS** [comment]
Is there any standard literature on the way you are calculating the ELBO? I can grasp your implementation until the logdet part but everything afterwards looks unfamiliar to me, I'm afraid - am I right that your implementation helps with numerical stability?

**Comment by willtebbutt** [comment]
Apologies for being non-responsive. I'm not aware of standard references on this -- you can derive it using the matrix inversion and determinant lemmas extensively. I need to write something up properly on this -- will try and make something available after the ICML deadline on the 4th of Feb.

**Comment by willtebbutt** [comment]
I've had a hunt through my notes, but can't find where I've derived it anywhere. The best explanation that I can give at present is therefore to say that
1. it _is_ just computing the standard bound introduced by Titsias (2009),
2. when you derive it, you have to make extensive use of the matrix inversion / determinant lemmas, and,
3. the trick used in section 3.4.3 of the GPML textbook (Rasmussen & Williams, 2006).

If I find my notes on this, I'll link them here!

**Comment by willtebbutt** [comment]
Closing in favour of the stuff we're doing in ApproximateGPs.jl
